/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    AFlex: typeof import('ant-design-vue/es')['Flex']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutSider: typeof import('ant-design-vue/es')['LayoutSider']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    AppSideBar: typeof import('./components/AppSideBar.vue')['default']
    ASpace: typeof import('ant-design-vue/es')['Space']
    ContentTemplate: typeof import('./components/pageviews/ContentTemplate.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    HelloWorldLogos: typeof import('./components/HelloWorldLogos.vue')['default']
    Page1: typeof import('./components/pageviews/Page1.vue')['default']
    Page2: typeof import('./components/pageviews/Page2.vue')['default']
    PageBox: typeof import('./components/pageviews/PageBox.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
