name: Build & Deploy

on:
  push:
    branches:
      - main

env:
  # DIST_LOCAL: '/home/runner/work/test-vite-vue/test-vite-vue/dist'
  DIST_LOCAL: 'dist/'
  DIST_REMOTE: '/usr/share/nginx/html/test-vite-vue-dist'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup pnpm
      uses: pnpm/action-setup@v4.0.0
      with:
        version: 9
        run_install: false

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'pnpm'

    - name: Install dependencies
      run: |
        pnpm install
    - name: Build project
      run: |
        pnpm build
    # - name: List build files
    #   run: |
    #     ls -al

    - name: Deploy to Nginx server
      uses: easingthemes/ssh-deploy@v5.1.0
      with:
        SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        REMOTE_HOST: ${{ secrets.SERVER_IP }}
        REMOTE_USER: ${{ secrets.SERVER_USER }}
        SOURCE: ${{ env.DIST_LOCAL }}
        TARGET: ${{ env.DIST_REMOTE }}
        ARGS: "-rltgoDzvO --delete"
      # uses: wangyucode/sftp-upload-action@v2.0.2
      # with:
      #   host: ${{ secrets.SERVER_IP }}
      #   username: ${{ secrets.SERVER_USER }}
      #   privateKey: ${{ secrets.PRIVATE_KEY }}
      #   localDir: ${{ env.DIST_LOCAL }}
      #   remoteDir: ${{ env.DIST_REMOTE }}
